# model
model: model.msg3d.Model
model_args:
  num_class: 82
  num_point: 53
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.mediapipe_joints.AdjMatrixGraph

device: 0
weights: config/signamed/version_15_08_2021/signamed_retrain_autsl_joint_motion_mediapipe-C3-xyc-train2.pt
