# COMPUTATION SERVER
IP_SERVER_COMPUTE: '172.19.56.82:56080'

# GLOOGLE CLOUD STORAGE.
VIDEO_FOLDER: './data/video'
VIDEO_COLAB_FOLDER: './data/video_colab'
ALLOWED_EXTENSIONS : ['mp4']
ALLOWED_MAX_SIZE : 20971520 # 20 (MB) * 1024 * 1024

# DATASET
DATASET_JSON : 'data/signs.json'